/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/requests/$id' | '/requests/new' | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/requests/$id' | '/requests/new' | '/requests'
  id: '__root__' | '/' | '/requests/$id' | '/requests/new' | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
